Feature/jssnmshdd 2883 webhooks module v2
nmshd/cns-connector pull request #23
Opened 2022-03-01 14:38 UTC by tnotheis

2022-03-02 09:25 UTC, tnotheis commented on config/default.json
> +            "displayName": "Webhooks (deprecated)",
Letzteres, denk ich

2022-03-02 09:39 UTC, jkoenig134 requested changes

2022-03-02 09:39 UTC, jkoenig134 commented on src/modules/webhooksV2/WebhooksModuleV2.ts
> +export interface WebhooksModuleConfiguration extends ConnectorRuntimeModuleConfiguration {
V2 im Namen fehlt

2022-03-02 09:39 UTC, jkoenig134 commented on src/modules/webhooksV2/WebhooksModuleV2.ts
> +export default class WebhooksModule extends ConnectorRuntimeModule<WebhooksModuleConfiguration> {
V2 im Namen fehlt

2022-03-02 09:59 UTC, jkoenig134 commented on src/modules/webhooksV2/WebhooksModuleV2.ts
> +            httpAgent: new AgentKeepAlive(),
Also wenn ich eine Schnittstelle aufmache bei der ich webhooks empfange würde ich nicht erwarten, dass der andere diese aufhält.

2022-03-02 10:10 UTC, jkoenig134 approved these changes

2022-03-02 10:21 UTC, jkoenig134 approved these changes

2022-03-02 11:30 UTC, jkoenig134 requested changes
Changelog fehlt

2022-03-03 07:33 UTC, jkoenig134 commented on CHANGELOG.md
> +-   new module: 'webhooksV2' (see https://enmeshed.eu/integrate/connector-configuration#webhooksV2 for more details)
schreib noch, dass das alte deprecated ist.

Und eigentlich  können wir die warnung mit dem blog post auch schon rausgeben wenn das alte Modul startet

2022-03-03 09:52 UTC, jkoenig134 commented on src/modules/webhooksV2/WebhooksModuleV2.ts
> +        const url = webhook.target.urlTemplate.fill({ trigger: trigger });
unten übergibst du den trigger ohne `trigger: trigger`, könntest du hier auch so machen

2022-03-03 10:54 UTC, jkoenig134 approved these changes

2022-03-03 10:55 UTC, jkoenig134 approved these changes

2022-03-04 09:12 UTC, merged