Feature/jssnmshdd 2977 routes for attributes
nmshd/cns-connector pull request #35
Opened 2022-06-02 14:09 UTC by jkoenig134

2022-06-02 16:30 UTC, tnotheis requested changes

2022-06-03 05:46 UTC, jkoenig134 commented on src/modules/coreHttpApi/openapi.yml
> +          description: The confidentiality of the attribute.
Das trifft doch bei den meisten anderen descriptions doch auch zu.

2022-06-03 05:48 UTC, tnotheis commented on src/modules/coreHttpApi/openapi.yml
> +          description: The confidentiality of the attribute.
Ja

2022-06-03 05:49 UTC, tnotheis commented on src/modules/coreHttpApi/openapi.yml
> +          description: The confidentiality of the attribute.
Können wir ruhig erstmal lassen, ist mir nur aufgefallen. Hat was von diesen unnötigen JSDoc Kommentaren

2022-06-03 06:26 UTC, tnotheis approved these changes

2022-06-03 06:37 UTC, merged