Refactor/extract http server as infrastructure
nmshd/cns-connector pull request #4
Opened 2021-11-16 14:37 UTC by jkoenig134

2021-11-16 15:19 UTC, tnotheis commented
Eventuell sollte das Konzept "infrastructure" bereits in der Runtime definiert sein. So wie "modules" auch (up for discussion, wollte ich nur mal in den Raum werfen, muss auch nciht gleich so umgesetzt werden).

2021-11-16 15:31 UTC, tnotheis requested changes

2021-11-16 15:31 UTC, tnotheis commented on config/default.json
> +            "infrastructure": ["httpServer"],
`requiredInfrastructure`?

2021-11-16 15:31 UTC, tnotheis commented on package.json
> +    "version": "2.1.0",
Eigentlich 3.0.0, oder?

2021-11-16 15:31 UTC, tnotheis commented on src/modules/coreHttpApi/CoreHttpApiModule.ts
> +        return this.runtime.httpServer!;
Warum ein private getter? Wieso speicherst du in init nicht einfach den Wert in einem Feld der Klasse?

2021-11-16 16:04 UTC, jkoenig134 commented on config/default.json
> +            "infrastructure": ["httpServer"],
finde ich ein bisschen verbose

2021-11-16 16:04 UTC, jkoenig134 commented on package.json
> +    "version": "2.1.0",
Hmm, von mir aus. Eigentlich wollten wir ja nicht solche Sprünge machen

2021-11-16 16:07 UTC, jkoenig134 commented on src/ConnectorRuntime.ts
> +    public httpServer?: HttpServer;
1. hatte ich gemacht, hatte dann aber nichts vereinfacht. Das gute hierran ist ja, dass du nicht mit nem getModuleBy name und nem cast darauf hoffen musst, dass die infrastruktur so aussieht wie du es gerne hättest.
2. not yet
3. das hab ich dann im modul selbst geklärt, der config key infrastructure / requiredInfrastructure / dependsOn wird ja aktuell noch nicht behandelt.

2021-11-16 16:08 UTC, jkoenig134 commented on src/modules/coreHttpApi/CoreHttpApiModule.ts
> +        if (!this.runtime.httpServer || !this.runtime.httpServer.isEnabled) {
Genau, das gibts halt aktuell nicht.

2021-11-17 14:07 UTC, tnotheis requested changes

2021-11-17 14:07 UTC, tnotheis commented on src/ConnectorRuntime.ts
> +            if (infrastructureConfiguration?.enabled) continue;
Ich glaub ich fänds übersichtlicher, wenn der Exception-Path innerhalb des `if`s wär. ;-)

2021-11-17 14:07 UTC, tnotheis commented on src/jsonSchemas/connectorConfig.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Wir sollten uns darauf einigen, ob wir die Datei formatieren oder nicht. Weil sonst gibts jedes mal nen riesigen diff.

2021-11-17 14:07 UTC, tnotheis commented on src/jsonSchemas/connectorConfig.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Sieht es für mich nur so aus oder ist da wirklich sehr viel verändert worden?

2021-11-17 14:07 UTC, tnotheis commented on .ci/buildAndPush.sh
> +
Du hast jetzt die Prüfung, ob jq installiert ist, aus writeBuildInformation.sh rausgenommen, aber nirgendwo wieder reingemacht, oder?

2021-11-17 14:16 UTC, jkoenig134 commented on src/jsonSchemas/connectorConfig.json
> +  "$schema": "http://json-schema.org/draft-07/schema#",
Wir müssen sie formatieren oder vom prettier excluden..

2021-11-17 14:21 UTC, jkoenig134 commented on src/ConnectorRuntime.ts
> +            if (infrastructureConfiguration?.enabled) continue;
ok

2021-11-17 14:24 UTC, jkoenig134 commented on .ci/buildAndPush.sh
> +
Aah, andere Datei 🍭

2021-11-17 15:55 UTC, tnotheis requested changes

2021-11-17 15:55 UTC, tnotheis commented on src/jsonSchemas/connectorConfig.json
> +    "$schema": "http://json-schema.org/draft-07/schema#",
Ziemlich viele Änderungen an der Datei. Ich frag mich wieso

2021-11-17 15:55 UTC, tnotheis commented on CHANGELOG.md
> +-   the httpServer configuration moved from `modules` to `infrastructure`
apikey ist required

2021-11-17 15:57 UTC, tnotheis approved these changes

2021-11-17 15:59 UTC, merged