Fix/relationship status "revoked" missing in openapi spec
nmshd/cns-connector pull request #71
Opened 2022-10-24 15:00 UTC by tnotheis

2022-10-24 15:02 UTC, tnotheis reviewed
Ich hab mal außerdem noch ein paar Requests "geilined", die nur einmal verwendet werden. Das haben wir bei allen anderen Routes auch so gemacht, nur bei den neuen Routes (Attributes und Requests) war es nicht so.

2022-10-24 15:04 UTC, tnotheis commented
Ach ja, und der eigentliche Grund für den PR war, dass wir scheinbar damals, als wir den Status "Terminated" einer Relationship entfernt haben, ausversehen auch den Status "Revoked" aus der openapi Definition entfernt haben. Es gibt den Status aber noch im `RelationshipDTO`. 

Wie auch immer das durchrutschen konnte.

2022-10-24 16:16 UTC, jkoenig134 requested changes
Version bump fehlt (neues openapi doc soll ja gepublisht werden)

2022-10-25 06:16 UTC, jkoenig134 approved these changes

2022-10-25 06:16 UTC, merged